import SupperAdminHeader from "@/components/view/Header/SupperAdminHeader";
import SupperAdminSideBar from "@/components/view/SideBar/SupperAdminSideBar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className={poppins.className}>
        <SupperAdminHeader />
        <SupperAdminSideBar>{children}</SupperAdminSideBar>
      </main>
    </>
  );
}
